#ifndef USER_INTERFACE_H
#define USER_INTERFACE_H

#include <GLFW/glfw3.h>

// keyboard input
#define CAMERA_ORBIT_KEY GLFW_KEY_LEFT_ALT
#define GRAB_KEY GLFW_KEY_G
#define SCALE_KEY GLFW_KEY_F
#define ROTATE_KEY GLFW_KEY_R
#define CURSOR_MOVE_KEY GLFW_KEY_C
#define CURSOR_JUMP_KEY GLFW_KEY_V
#define MERGE_POINTS_KEY GLFW_KEY_M


#endif